name: test

on: [push, pull_request]

jobs:
  test:
    name: Run tests

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: npm test

      - name: Generate coverage report
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == '16.x' }}
        run: npm run cover

      - name: Upload coverage report to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == '16.x' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unit,${{ matrix.node-version }},${{ matrix.os }}
          fail_ci_if_error: true
          verbose: true
